---
title: "Forecast Accuracy Dashboard"
runtime: shiny
output:
  flexdashboard::flex_dashboard: null
  orientation: rows
  vertical_layout: fill
  source_code: embed
  theme: cosmo
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(magrittr)
library(reshape2)
library(skimr)
library(janitor)
library(lubridate)
library(plotly)
library(DT)
library(rsconnect)
library(ggside)
library(shiny)
library(shinyWidgets)
library(vroom)

```

```{r, include=FALSE} 

load("mega_data_by_r_10.2022.rds")
mega_data_by_r <- mega_data_by_r

options(shiny.maxRequestSize = 120*1024^2)

```





# Accy & Fcst Pivot (Lag)

Inputs {.sidebar data-width=500}
-----------------------------------------------------------------------

```{r, echo = FALSE}
# product_platform <- unique(sort(mega_data_by_r$product_platform_name))
# pickerInput(inputId = "product_platform", label = "Product Platform", choices = product_platform,
#                     options = list("actions-box" = TRUE), multiple = TRUE, width = 500, selected = product_platform)
# 
# product_group <- unique(sort(mega_data_by_r$product_group_code))
# pickerInput(inputId = "product_group", label = "Product Group", choices = product_group,
#                     options = list("actions-box" = TRUE), multiple = TRUE, width = 500, selected = product_group)
# 
# sku <- unique(sort(mega_data_by_r$product_label_sku_code))
# pickerInput(inputId = "sku", label = "SKU", choices = sku,
#                     options = list("actions-box" = TRUE), multiple = TRUE, width = 500, selected = sku)
# 
# 
# label <- unique(sort(mega_data_by_r$label))
# pickerInput(inputId = "label", label = "Label", choices = label,
#                     options = list("actions-box" = TRUE), multiple = TRUE, width = 500, selected = label)
# 
# 
# campus <- unique(sort(mega_data_by_r$product_manufacturing_location_name))
# pickerInput(inputId = "campus", label = "Campus", choices = campus,
#                     options = list("actions-box" = TRUE), multiple = TRUE, width = 500, selected = campus)

product_platform <- unique(sort(mega_data_by_r$product_platform_name))
selectInput(inputId = "product_platform", label = "Product Platform", choices = product_platform,
                  multiple = TRUE, width = 500, selected = product_platform)

product_group <- unique(sort(mega_data_by_r$product_group_code))
selectInput(inputId = "product_group", label = "Product Group", choices = product_group,
                    multiple = TRUE, width = 500, selected = product_group)

sku <- unique(sort(mega_data_by_r$product_label_sku_code))
selectInput(inputId = "sku", label = "SKU", choices = sku,
                    multiple = TRUE, width = 500, selected = sku)


label <- unique(sort(mega_data_by_r$label))
selectInput(inputId = "label", label = "Label", choices = label,
                    multiple = TRUE, width = 500, selected = label)


campus <- unique(sort(mega_data_by_r$product_manufacturing_location_name))
selectInput(inputId = "campus", label = "Campus", choices = campus,
                    multiple = TRUE, width = 500, selected = campus)



```



Row
-----------------------------------------------------------------------

```{r, echo=FALSE}

renderDataTable({
  
  accy_fcst_pivot <-   dplyr::filter(mega_data_by_r, product_platform_name == input$product_platform |
                                                     product_group_code == input$product_group |
                                                     product_label_sku_code == input$sku | 
                                                     label == input$label | 
                                                     product_manufacturing_location_name == input$campus) 
  
  accy_fcst_pivot_a <- reshape2::dcast(accy_fcst_pivot, lag ~ forecast_per, value.var = "adjusted_forecast_cases", sum) %>% 
    dplyr::mutate(values = "Adjusted Forecasted Cases") %>% 
    dplyr::relocate(lag, values) 
    
  
  accy_fcst_pivot_b <- reshape2::dcast(accy_fcst_pivot, lag ~ forecast_per, value.var = "actual", sum) %>%
    dplyr::mutate(values = "Actual Cases") %>% 
    dplyr::relocate(lag, values)
  
  accy_fcst_pivot_c <- reshape2::dcast(accy_fcst_pivot, lag ~ forecast_per, value.var = "as_ordered_quantity", sum) %>% 
    dplyr::mutate(values = "Final Ordered Qty Cases") %>% 
    dplyr::relocate(lag, values) 
  
  accy_fcst_pivot_d <- reshape2::dcast(accy_fcst_pivot, lag ~ forecast_per, value.var = "as_original_ordered_quantity", sum) %>% 
    dplyr::mutate(values = "Original Ordered Qty Cases") %>% 
    dplyr::relocate(lag, values)
  
  
  
  accy_fcst_pivot_2 <- rbind(accy_fcst_pivot_a, accy_fcst_pivot_b, accy_fcst_pivot_c, accy_fcst_pivot_d) %>% 
    dplyr::arrange(desc(lag)) 
   
  
  DT::datatable(accy_fcst_pivot_2,
                extensions = "Buttons",
                options = list(scrollY = TRUE,
                               dom = "Blfrtip",
                               buttons = c("copy", "csv", "excel")))
  
  

  
})


```


# Currently, I have a problem with filter... shiny provided app would work: find the best filter funtions. 

